sudo: required

language: ruby

services:
  - docker

script:
#  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker build -t acd_cli .
  - docker images
#  - if [ "$TRAVIS_BRANCH" == "master" ]; then
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push kune/acd_cli;
#    fi
