sudo: required

language: ruby

services:
  - docker

script:
  - docker build -t acd_cli .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push kune/acd_cli;
    fi
